### ISSUE TITLE
Finish Dropbox-service and delete permit service

### ISSUE THREAD

**Issue by nettashviro** [meateam/dropbox-service#2]
- [x] check if the connection pool grpc is working for spike-service and user-service (reconnection, round-robin and related errors) - need to check at kubernetes 
- [x] add dropbox-service helm-chart in drive-project and remove permit-service helm chart (remember to test healthchecks)
- [x] add test
- [x] Add documentation 
- [x] add user-service implementation
- [x] add different envs approvals at config file
- [x] add dropbox-service implentation at api-gtw and remove permit-sevice and approval-info from user-service

**Comment by Shahar-Y** [comment]
Closing. Done.Good job @nettashviro
